package com.evertvd.bienes.modelo.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.evertvd.bienes.modelo.Empresa;

import com.evertvd.bienes.modelo.Catalogo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATALOGO".
*/
public class CatalogoDao extends AbstractDao<Catalogo, Long> {

    public static final String TABLENAME = "CATALOGO";

    /**
     * Properties of entity Catalogo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Codigo = new Property(1, String.class, "codigo", false, "CODIGO");
        public final static Property Catalogo = new Property(2, String.class, "catalogo", false, "CATALOGO");
        public final static Property Empresa_id2 = new Property(3, Long.class, "empresa_id2", false, "EMPRESA_ID2");
    }

    private DaoSession daoSession;

    private Query<Catalogo> empresa_CatalogoListQuery;

    public CatalogoDao(DaoConfig config) {
        super(config);
    }
    
    public CatalogoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATALOGO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CODIGO\" TEXT," + // 1: codigo
                "\"CATALOGO\" TEXT," + // 2: catalogo
                "\"EMPRESA_ID2\" INTEGER);"); // 3: empresa_id2
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_CATALOGO_EMPRESA_ID2 ON CATALOGO" +
                " (\"EMPRESA_ID2\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATALOGO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Catalogo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String codigo = entity.getCodigo();
        if (codigo != null) {
            stmt.bindString(2, codigo);
        }
 
        String catalogo = entity.getCatalogo();
        if (catalogo != null) {
            stmt.bindString(3, catalogo);
        }
 
        Long empresa_id2 = entity.getEmpresa_id2();
        if (empresa_id2 != null) {
            stmt.bindLong(4, empresa_id2);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Catalogo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String codigo = entity.getCodigo();
        if (codigo != null) {
            stmt.bindString(2, codigo);
        }
 
        String catalogo = entity.getCatalogo();
        if (catalogo != null) {
            stmt.bindString(3, catalogo);
        }
 
        Long empresa_id2 = entity.getEmpresa_id2();
        if (empresa_id2 != null) {
            stmt.bindLong(4, empresa_id2);
        }
    }

    @Override
    protected final void attachEntity(Catalogo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Catalogo readEntity(Cursor cursor, int offset) {
        Catalogo entity = new Catalogo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // codigo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // catalogo
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // empresa_id2
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Catalogo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCodigo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCatalogo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEmpresa_id2(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Catalogo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Catalogo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Catalogo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "catalogoList" to-many relationship of Empresa. */
    public List<Catalogo> _queryEmpresa_CatalogoList(Long empresa_id2) {
        synchronized (this) {
            if (empresa_CatalogoListQuery == null) {
                QueryBuilder<Catalogo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Empresa_id2.eq(null));
                empresa_CatalogoListQuery = queryBuilder.build();
            }
        }
        Query<Catalogo> query = empresa_CatalogoListQuery.forCurrentThread();
        query.setParameter(0, empresa_id2);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEmpresaDao().getAllColumns());
            builder.append(" FROM CATALOGO T");
            builder.append(" LEFT JOIN EMPRESA T0 ON T.\"EMPRESA_ID2\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Catalogo loadCurrentDeep(Cursor cursor, boolean lock) {
        Catalogo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Empresa empresa = loadCurrentOther(daoSession.getEmpresaDao(), cursor, offset);
        entity.setEmpresa(empresa);

        return entity;    
    }

    public Catalogo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Catalogo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Catalogo> list = new ArrayList<Catalogo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Catalogo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Catalogo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
