package com.evertvd.bienes.modelo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.evertvd.bienes.modelo.Activo;
import com.evertvd.bienes.modelo.Historial;

import com.evertvd.bienes.modelo.dao.ActivoDao;
import com.evertvd.bienes.modelo.dao.HistorialDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig activoDaoConfig;
    private final DaoConfig historialDaoConfig;

    private final ActivoDao activoDao;
    private final HistorialDao historialDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        activoDaoConfig = daoConfigMap.get(ActivoDao.class).clone();
        activoDaoConfig.initIdentityScope(type);

        historialDaoConfig = daoConfigMap.get(HistorialDao.class).clone();
        historialDaoConfig.initIdentityScope(type);

        activoDao = new ActivoDao(activoDaoConfig, this);
        historialDao = new HistorialDao(historialDaoConfig, this);

        registerDao(Activo.class, activoDao);
        registerDao(Historial.class, historialDao);
    }
    
    public void clear() {
        activoDaoConfig.clearIdentityScope();
        historialDaoConfig.clearIdentityScope();
    }

    public ActivoDao getActivoDao() {
        return activoDao;
    }

    public HistorialDao getHistorialDao() {
        return historialDao;
    }

}
