package com.evertvd.bienes.modelo.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.evertvd.bienes.modelo.Empresa;

import com.evertvd.bienes.modelo.Departamento;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEPARTAMENTO".
*/
public class DepartamentoDao extends AbstractDao<Departamento, Long> {

    public static final String TABLENAME = "DEPARTAMENTO";

    /**
     * Properties of entity Departamento.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Departamento = new Property(1, String.class, "departamento", false, "DEPARTAMENTO");
        public final static Property Empresa_id = new Property(2, Long.class, "empresa_id", false, "EMPRESA_ID");
    }

    private DaoSession daoSession;

    private Query<Departamento> empresa_DepartamentoListQuery;

    public DepartamentoDao(DaoConfig config) {
        super(config);
    }
    
    public DepartamentoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEPARTAMENTO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DEPARTAMENTO\" TEXT," + // 1: departamento
                "\"EMPRESA_ID\" INTEGER);"); // 2: empresa_id
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_DEPARTAMENTO_EMPRESA_ID ON DEPARTAMENTO" +
                " (\"EMPRESA_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEPARTAMENTO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Departamento entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String departamento = entity.getDepartamento();
        if (departamento != null) {
            stmt.bindString(2, departamento);
        }
 
        Long empresa_id = entity.getEmpresa_id();
        if (empresa_id != null) {
            stmt.bindLong(3, empresa_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Departamento entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String departamento = entity.getDepartamento();
        if (departamento != null) {
            stmt.bindString(2, departamento);
        }
 
        Long empresa_id = entity.getEmpresa_id();
        if (empresa_id != null) {
            stmt.bindLong(3, empresa_id);
        }
    }

    @Override
    protected final void attachEntity(Departamento entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Departamento readEntity(Cursor cursor, int offset) {
        Departamento entity = new Departamento( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // departamento
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // empresa_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Departamento entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDepartamento(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEmpresa_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Departamento entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Departamento entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Departamento entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "departamentoList" to-many relationship of Empresa. */
    public List<Departamento> _queryEmpresa_DepartamentoList(Long empresa_id) {
        synchronized (this) {
            if (empresa_DepartamentoListQuery == null) {
                QueryBuilder<Departamento> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Empresa_id.eq(null));
                empresa_DepartamentoListQuery = queryBuilder.build();
            }
        }
        Query<Departamento> query = empresa_DepartamentoListQuery.forCurrentThread();
        query.setParameter(0, empresa_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEmpresaDao().getAllColumns());
            builder.append(" FROM DEPARTAMENTO T");
            builder.append(" LEFT JOIN EMPRESA T0 ON T.\"EMPRESA_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Departamento loadCurrentDeep(Cursor cursor, boolean lock) {
        Departamento entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Empresa empresa = loadCurrentOther(daoSession.getEmpresaDao(), cursor, offset);
        entity.setEmpresa(empresa);

        return entity;    
    }

    public Departamento loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Departamento> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Departamento> list = new ArrayList<Departamento>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Departamento> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Departamento> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
