package com.evertvd.bienes.modelo.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.evertvd.bienes.modelo.Departamento;

import com.evertvd.bienes.modelo.Sede;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEDE".
*/
public class SedeDao extends AbstractDao<Sede, Long> {

    public static final String TABLENAME = "SEDE";

    /**
     * Properties of entity Sede.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sede = new Property(1, String.class, "sede", false, "SEDE");
        public final static Property Departamento_id = new Property(2, Long.class, "departamento_id", false, "DEPARTAMENTO_ID");
    }

    private DaoSession daoSession;

    private Query<Sede> departamento_SedeListQuery;

    public SedeDao(DaoConfig config) {
        super(config);
    }
    
    public SedeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEDE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SEDE\" TEXT," + // 1: sede
                "\"DEPARTAMENTO_ID\" INTEGER);"); // 2: departamento_id
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_SEDE_DEPARTAMENTO_ID ON SEDE" +
                " (\"DEPARTAMENTO_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEDE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Sede entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sede = entity.getSede();
        if (sede != null) {
            stmt.bindString(2, sede);
        }
 
        Long departamento_id = entity.getDepartamento_id();
        if (departamento_id != null) {
            stmt.bindLong(3, departamento_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Sede entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sede = entity.getSede();
        if (sede != null) {
            stmt.bindString(2, sede);
        }
 
        Long departamento_id = entity.getDepartamento_id();
        if (departamento_id != null) {
            stmt.bindLong(3, departamento_id);
        }
    }

    @Override
    protected final void attachEntity(Sede entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Sede readEntity(Cursor cursor, int offset) {
        Sede entity = new Sede( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sede
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // departamento_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Sede entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSede(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDepartamento_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Sede entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Sede entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Sede entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "sedeList" to-many relationship of Departamento. */
    public List<Sede> _queryDepartamento_SedeList(Long departamento_id) {
        synchronized (this) {
            if (departamento_SedeListQuery == null) {
                QueryBuilder<Sede> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Departamento_id.eq(null));
                departamento_SedeListQuery = queryBuilder.build();
            }
        }
        Query<Sede> query = departamento_SedeListQuery.forCurrentThread();
        query.setParameter(0, departamento_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDepartamentoDao().getAllColumns());
            builder.append(" FROM SEDE T");
            builder.append(" LEFT JOIN DEPARTAMENTO T0 ON T.\"DEPARTAMENTO_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Sede loadCurrentDeep(Cursor cursor, boolean lock) {
        Sede entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Departamento departamento = loadCurrentOther(daoSession.getDepartamentoDao(), cursor, offset);
        entity.setDepartamento(departamento);

        return entity;    
    }

    public Sede loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Sede> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Sede> list = new ArrayList<Sede>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Sede> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Sede> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
