package com.evertvd.bienes.modelo.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.evertvd.bienes.modelo.Sede;

import com.evertvd.bienes.modelo.Ubicacion;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UBICACION".
*/
public class UbicacionDao extends AbstractDao<Ubicacion, Long> {

    public static final String TABLENAME = "UBICACION";

    /**
     * Properties of entity Ubicacion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Ubicacion = new Property(1, String.class, "ubicacion", false, "UBICACION");
        public final static Property Sede_id = new Property(2, Long.class, "sede_id", false, "SEDE_ID");
    }

    private DaoSession daoSession;

    private Query<Ubicacion> sede_UbicacionListQuery;

    public UbicacionDao(DaoConfig config) {
        super(config);
    }
    
    public UbicacionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UBICACION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UBICACION\" TEXT," + // 1: ubicacion
                "\"SEDE_ID\" INTEGER);"); // 2: sede_id
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_UBICACION_SEDE_ID ON UBICACION" +
                " (\"SEDE_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UBICACION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Ubicacion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ubicacion = entity.getUbicacion();
        if (ubicacion != null) {
            stmt.bindString(2, ubicacion);
        }
 
        Long sede_id = entity.getSede_id();
        if (sede_id != null) {
            stmt.bindLong(3, sede_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Ubicacion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ubicacion = entity.getUbicacion();
        if (ubicacion != null) {
            stmt.bindString(2, ubicacion);
        }
 
        Long sede_id = entity.getSede_id();
        if (sede_id != null) {
            stmt.bindLong(3, sede_id);
        }
    }

    @Override
    protected final void attachEntity(Ubicacion entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Ubicacion readEntity(Cursor cursor, int offset) {
        Ubicacion entity = new Ubicacion( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ubicacion
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // sede_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Ubicacion entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUbicacion(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSede_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Ubicacion entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Ubicacion entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Ubicacion entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "ubicacionList" to-many relationship of Sede. */
    public List<Ubicacion> _querySede_UbicacionList(Long sede_id) {
        synchronized (this) {
            if (sede_UbicacionListQuery == null) {
                QueryBuilder<Ubicacion> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Sede_id.eq(null));
                sede_UbicacionListQuery = queryBuilder.build();
            }
        }
        Query<Ubicacion> query = sede_UbicacionListQuery.forCurrentThread();
        query.setParameter(0, sede_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSedeDao().getAllColumns());
            builder.append(" FROM UBICACION T");
            builder.append(" LEFT JOIN SEDE T0 ON T.\"SEDE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Ubicacion loadCurrentDeep(Cursor cursor, boolean lock) {
        Ubicacion entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Sede sede = loadCurrentOther(daoSession.getSedeDao(), cursor, offset);
        entity.setSede(sede);

        return entity;    
    }

    public Ubicacion loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Ubicacion> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Ubicacion> list = new ArrayList<Ubicacion>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Ubicacion> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Ubicacion> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
