package com.evertvd.bienes.modelo;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.evertvd.bienes.modelo.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

import com.evertvd.bienes.modelo.dao.ActivoDao;
import com.evertvd.bienes.modelo.dao.HistorialDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ACTIVO".
 */
@Entity(active = true)
public class Activo {

    @Id(autoincrement = true)
    private Long id;
    private String codigo;
    private String codigobarra;
    private String empresa;
    private String departamento;
    private String sede;
    private String ubicacion;
    private String codcatalogo;
    private String catalogo;
    private String placa;
    private String marca;
    private String modelo;
    private String serie;
    private String foto;
    private String responsable;
    private String tipoActivo;
    private String activopadre;
    private String codCentro;
    private String centro;
    private String cuenta;
    private String estado;
    private String expediente;
    private String ordencompra;
    private String factura;
    private String fechacompra;
    private String observacion;
    private Integer seleccionado;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient ActivoDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "activo_id")
    })
    private List<Historial> historialList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Activo() {
    }

    public Activo(Long id) {
        this.id = id;
    }

    @Generated
    public Activo(Long id, String codigo, String codigobarra, String empresa, String departamento, String sede, String ubicacion, String codcatalogo, String catalogo, String placa, String marca, String modelo, String serie, String foto, String responsable, String tipoActivo, String activopadre, String codCentro, String centro, String cuenta, String estado, String expediente, String ordencompra, String factura, String fechacompra, String observacion, Integer seleccionado) {
        this.id = id;
        this.codigo = codigo;
        this.codigobarra = codigobarra;
        this.empresa = empresa;
        this.departamento = departamento;
        this.sede = sede;
        this.ubicacion = ubicacion;
        this.codcatalogo = codcatalogo;
        this.catalogo = catalogo;
        this.placa = placa;
        this.marca = marca;
        this.modelo = modelo;
        this.serie = serie;
        this.foto = foto;
        this.responsable = responsable;
        this.tipoActivo = tipoActivo;
        this.activopadre = activopadre;
        this.codCentro = codCentro;
        this.centro = centro;
        this.cuenta = cuenta;
        this.estado = estado;
        this.expediente = expediente;
        this.ordencompra = ordencompra;
        this.factura = factura;
        this.fechacompra = fechacompra;
        this.observacion = observacion;
        this.seleccionado = seleccionado;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getActivoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigobarra() {
        return codigobarra;
    }

    public void setCodigobarra(String codigobarra) {
        this.codigobarra = codigobarra;
    }

    public String getEmpresa() {
        return empresa;
    }

    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    public String getDepartamento() {
        return departamento;
    }

    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    public String getSede() {
        return sede;
    }

    public void setSede(String sede) {
        this.sede = sede;
    }

    public String getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    public String getCodcatalogo() {
        return codcatalogo;
    }

    public void setCodcatalogo(String codcatalogo) {
        this.codcatalogo = codcatalogo;
    }

    public String getCatalogo() {
        return catalogo;
    }

    public void setCatalogo(String catalogo) {
        this.catalogo = catalogo;
    }

    public String getPlaca() {
        return placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getSerie() {
        return serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public String getResponsable() {
        return responsable;
    }

    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }

    public String getTipoActivo() {
        return tipoActivo;
    }

    public void setTipoActivo(String tipoActivo) {
        this.tipoActivo = tipoActivo;
    }

    public String getActivopadre() {
        return activopadre;
    }

    public void setActivopadre(String activopadre) {
        this.activopadre = activopadre;
    }

    public String getCodCentro() {
        return codCentro;
    }

    public void setCodCentro(String codCentro) {
        this.codCentro = codCentro;
    }

    public String getCentro() {
        return centro;
    }

    public void setCentro(String centro) {
        this.centro = centro;
    }

    public String getCuenta() {
        return cuenta;
    }

    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getExpediente() {
        return expediente;
    }

    public void setExpediente(String expediente) {
        this.expediente = expediente;
    }

    public String getOrdencompra() {
        return ordencompra;
    }

    public void setOrdencompra(String ordencompra) {
        this.ordencompra = ordencompra;
    }

    public String getFactura() {
        return factura;
    }

    public void setFactura(String factura) {
        this.factura = factura;
    }

    public String getFechacompra() {
        return fechacompra;
    }

    public void setFechacompra(String fechacompra) {
        this.fechacompra = fechacompra;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public Integer getSeleccionado() {
        return seleccionado;
    }

    public void setSeleccionado(Integer seleccionado) {
        this.seleccionado = seleccionado;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Historial> getHistorialList() {
        if (historialList == null) {
            __throwIfDetached();
            HistorialDao targetDao = daoSession.getHistorialDao();
            List<Historial> historialListNew = targetDao._queryActivo_HistorialList(id);
            synchronized (this) {
                if(historialList == null) {
                    historialList = historialListNew;
                }
            }
        }
        return historialList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetHistorialList() {
        historialList = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
